server:
  port: 8082
spring:
  application:
    name: jpassmcrud
  datasource:
    driver-class-name: org.driver.PostgresDriver
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: ORACLECT
    password: ORACLECT
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: ORACLE
    database-platform: 77
    show-sql: true
    open-in-view: false
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html